// Code generated by protoc-gen-go.
// source: main.proto
// DO NOT EDIT!

/*
Package babl is a generated protocol buffer package.

It is generated from these files:
	main.proto

It has these top-level messages:
	InfoRequest
	InfoResponse
	UploadRequest
	UploadResponse
*/
package babl

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InfoRequest struct {
}

func (m *InfoRequest) Reset()                    { *m = InfoRequest{} }
func (m *InfoRequest) String() string            { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()               {}
func (*InfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type InfoResponse struct {
	Version      string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	TotalStorage uint32 `protobuf:"varint,10,opt,name=total_storage,json=totalStorage" json:"total_storage,omitempty"`
	FreeStorage  uint32 `protobuf:"varint,11,opt,name=free_storage,json=freeStorage" json:"free_storage,omitempty"`
}

func (m *InfoResponse) Reset()                    { *m = InfoResponse{} }
func (m *InfoResponse) String() string            { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()               {}
func (*InfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type UploadRequest struct {
	Chunk          []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	TotalBytesSent uint64 `protobuf:"varint,2,opt,name=total_bytes_sent,json=totalBytesSent" json:"total_bytes_sent,omitempty"`
	Complete       bool   `protobuf:"varint,3,opt,name=complete" json:"complete,omitempty"`
}

func (m *UploadRequest) Reset()                    { *m = UploadRequest{} }
func (m *UploadRequest) String() string            { return proto.CompactTextString(m) }
func (*UploadRequest) ProtoMessage()               {}
func (*UploadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type UploadResponse struct {
	BlobId   uint64 `protobuf:"varint,1,opt,name=blob_id,json=blobId" json:"blob_id,omitempty"`
	BlobUrl  string `protobuf:"bytes,2,opt,name=blob_url,json=blobUrl" json:"blob_url,omitempty"`
	Complete bool   `protobuf:"varint,3,opt,name=complete" json:"complete,omitempty"`
	Success  bool   `protobuf:"varint,4,opt,name=success" json:"success,omitempty"`
	Error    string `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`
}

func (m *UploadResponse) Reset()                    { *m = UploadResponse{} }
func (m *UploadResponse) String() string            { return proto.CompactTextString(m) }
func (*UploadResponse) ProtoMessage()               {}
func (*UploadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*InfoRequest)(nil), "babl.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "babl.InfoResponse")
	proto.RegisterType((*UploadRequest)(nil), "babl.UploadRequest")
	proto.RegisterType((*UploadResponse)(nil), "babl.UploadResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Storage service

type StorageClient interface {
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
	Upload(ctx context.Context, opts ...grpc.CallOption) (Storage_UploadClient, error)
}

type storageClient struct {
	cc *grpc.ClientConn
}

func NewStorageClient(cc *grpc.ClientConn) StorageClient {
	return &storageClient{cc}
}

func (c *storageClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := grpc.Invoke(ctx, "/babl.Storage/Info", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageClient) Upload(ctx context.Context, opts ...grpc.CallOption) (Storage_UploadClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Storage_serviceDesc.Streams[0], c.cc, "/babl.Storage/Upload", opts...)
	if err != nil {
		return nil, err
	}
	x := &storageUploadClient{stream}
	return x, nil
}

type Storage_UploadClient interface {
	Send(*UploadRequest) error
	Recv() (*UploadResponse, error)
	grpc.ClientStream
}

type storageUploadClient struct {
	grpc.ClientStream
}

func (x *storageUploadClient) Send(m *UploadRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *storageUploadClient) Recv() (*UploadResponse, error) {
	m := new(UploadResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Storage service

type StorageServer interface {
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
	Upload(Storage_UploadServer) error
}

func RegisterStorageServer(s *grpc.Server, srv StorageServer) {
	s.RegisterService(&_Storage_serviceDesc, srv)
}

func _Storage_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/babl.Storage/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Storage_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageServer).Upload(&storageUploadServer{stream})
}

type Storage_UploadServer interface {
	Send(*UploadResponse) error
	Recv() (*UploadRequest, error)
	grpc.ServerStream
}

type storageUploadServer struct {
	grpc.ServerStream
}

func (x *storageUploadServer) Send(m *UploadResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *storageUploadServer) Recv() (*UploadRequest, error) {
	m := new(UploadRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Storage_serviceDesc = grpc.ServiceDesc{
	ServiceName: "babl.Storage",
	HandlerType: (*StorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _Storage_Info_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _Storage_Upload_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("main.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x92, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x31, 0xa4, 0xff, 0xae, 0x49, 0x05, 0xa6, 0x12, 0xa6, 0x53, 0x08, 0x4b, 0xa6, 0x82,
	0x60, 0x62, 0x65, 0xeb, 0xea, 0xaa, 0x73, 0x95, 0xa4, 0x57, 0xa8, 0xea, 0xda, 0xc1, 0x76, 0x90,
	0xf8, 0x16, 0x7c, 0x64, 0x64, 0x3b, 0xa9, 0xda, 0x85, 0xf1, 0xfd, 0xee, 0x25, 0xcf, 0xf7, 0x6c,
	0x80, 0x43, 0xb1, 0x93, 0xf3, 0x5a, 0x2b, 0xab, 0x68, 0x54, 0x16, 0xa5, 0xc8, 0x12, 0x18, 0x2f,
	0xe4, 0x56, 0x71, 0xfc, 0x6a, 0xd0, 0xd8, 0xac, 0x86, 0x38, 0x48, 0x53, 0x2b, 0x69, 0x90, 0x32,
	0x18, 0x7c, 0xa3, 0x36, 0x3b, 0x25, 0x19, 0x49, 0x49, 0x3e, 0xe2, 0x9d, 0xa4, 0x8f, 0x90, 0x58,
	0x65, 0x0b, 0xb1, 0x36, 0x56, 0xe9, 0xe2, 0x03, 0x19, 0xa4, 0x24, 0x4f, 0x78, 0xec, 0xe1, 0x32,
	0x30, 0xfa, 0x00, 0xf1, 0x56, 0x23, 0x1e, 0x3d, 0x63, 0xef, 0x19, 0x3b, 0xd6, 0x5a, 0xb2, 0x3d,
	0x24, 0xab, 0x5a, 0xa8, 0x62, 0xd3, 0x1e, 0x81, 0x4e, 0xa1, 0x57, 0x7d, 0x36, 0x72, 0xef, 0x03,
	0x63, 0x1e, 0x04, 0xcd, 0xe1, 0x3a, 0xc4, 0x95, 0x3f, 0x16, 0xcd, 0xda, 0xa0, 0xb4, 0xec, 0x32,
	0x25, 0x79, 0xc4, 0x27, 0x9e, 0xbf, 0x3b, 0xbc, 0x44, 0x69, 0xe9, 0x0c, 0x86, 0x95, 0x3a, 0xd4,
	0x02, 0x2d, 0xb2, 0xab, 0x94, 0xe4, 0x43, 0x7e, 0xd4, 0xd9, 0x2f, 0x81, 0x49, 0x97, 0xd6, 0x6e,
	0x78, 0x07, 0x83, 0x52, 0xa8, 0x72, 0xbd, 0xdb, 0xf8, 0xc0, 0x88, 0xf7, 0x9d, 0x5c, 0x6c, 0xe8,
	0x3d, 0x0c, 0xfd, 0xa0, 0xd1, 0xc2, 0x27, 0x8d, 0xb8, 0x37, 0xae, 0xb4, 0xf8, 0x2f, 0xc2, 0x35,
	0x66, 0x9a, 0xaa, 0x42, 0x63, 0x58, 0xe4, 0x47, 0x9d, 0x74, 0x8b, 0xa1, 0xd6, 0x4a, 0xb3, 0x9e,
	0xff, 0x5b, 0x10, 0x2f, 0x0d, 0x0c, 0xba, 0xb6, 0x9e, 0x20, 0x72, 0xe5, 0xd3, 0x9b, 0xb9, 0xbb,
	0x9a, 0xf9, 0xc9, 0xbd, 0xcc, 0xe8, 0x29, 0x0a, 0x27, 0xcf, 0x2e, 0xe8, 0x1b, 0xf4, 0xc3, 0x36,
	0xf4, 0x36, 0xcc, 0xcf, 0x9a, 0x9c, 0x4d, 0xcf, 0x61, 0xf7, 0x59, 0x4e, 0x9e, 0x49, 0xd9, 0xf7,
	0x8f, 0xe0, 0xf5, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xa5, 0x29, 0x92, 0xc6, 0x12, 0x02, 0x00, 0x00,
}
